### ISSUE TITLE
Is it possible to help me 'make' your package?

### ISSUE THREAD

**Issue by dikke** [xdsopl/spectrum#1]
Hi there

I am currently running Ubuntu 12.04. I have installed packages:
'fftw2', 'fftw-dev', 'fftw-doc', 'fftw-3.3.4'

However, when I try to make your master-files, it return me errors:
root@ubuntu:~/spectrum-master# make
cc -lm -lasound -L/usr/lib/x86_64-linux-gnu -lSDL -lfftw3f -lm    spectrum.o mmap_file.o pcm.o wav.o alsa.o window.o stft.o cqt.o trans.o   -o spectrum
spectrum.o: In function `handle_events':
/home/userKum/spectrum-master/spectrum.c:27: undefined reference to`SDL_PollEvent'
spectrum.o: In function `srgb':
/home/userKum/spectrum-master/spectrum.c:78: undefined reference to`__powf_finite'
/home/userKum/spectrum-master/spectrum.c:76: undefined reference to `__powf_finite'
/home/userKum/spectrum-master/spectrum.c:77: undefined reference to`__powf_finite'
spectrum.o: In function `main':
/home/userKum/spectrum-master/spectrum.c:126: undefined reference to`SDL_Init'
/home/userKum/spectrum-master/spectrum.c:127: undefined reference to `SDL_SetVideoMode'
/home/userKum/spectrum-master/spectrum.c:143: undefined reference to`SDL_WM_SetCaption'
/home/userKum/spectrum-master/spectrum.c:144: undefined reference to `SDL_EnableKeyRepeat'
/home/userKum/spectrum-master/spectrum.c:199: undefined reference to`__log10f_finite'
/home/userKum/spectrum-master/spectrum.c:157: undefined reference to `SDL_Flip'
/home/userKum/spectrum-master/spectrum.c:158: undefined reference to`SDL_Delay'
alsa.o: In function `write_alsa':
/home/userKum/spectrum-master/alsa.c:71: undefined reference to`snd_pcm_writei'
/home/userKum/spectrum-master/alsa.c:72: undefined reference to `snd_pcm_prepare'
alsa.o: In function`read_alsa':
/home/userKum/spectrum-master/alsa.c:54: undefined reference to `snd_pcm_readi'
/home/userKum/spectrum-master/alsa.c:55: undefined reference to`snd_pcm_prepare'
alsa.o: In function `close_alsa':
/home/userKum/spectrum-master/alsa.c:26: undefined reference to`snd_pcm_drain'
/home/userKum/spectrum-master/alsa.c:27: undefined reference to `snd_pcm_close'
alsa.o: In function`open_alsa_read':
/home/userKum/spectrum-master/alsa.c:92: undefined reference to `snd_pcm_hw_params_sizeof'
/home/userKum/spectrum-master/alsa.c:92: undefined reference to`snd_pcm_hw_params_sizeof'
/home/userKum/spectrum-master/alsa.c:94: undefined reference to `snd_pcm_open'
/home/userKum/spectrum-master/alsa.c:100: undefined reference to`snd_pcm_hw_params_any'
/home/userKum/spectrum-master/alsa.c:107: undefined reference to `snd_pcm_hw_params_set_access'
/home/userKum/spectrum-master/alsa.c:114: undefined reference to`snd_pcm_hw_params_set_format'
/home/userKum/spectrum-master/alsa.c:121: undefined reference to `snd_pcm_hw_params_set_rate_resample'
/home/userKum/spectrum-master/alsa.c:130: undefined reference to`snd_pcm_hw_params_set_rate_min'
/home/userKum/spectrum-master/alsa.c:109: undefined reference to `snd_pcm_close'
/home/userKum/spectrum-master/alsa.c:137: undefined reference to`snd_pcm_hw_params'
/home/userKum/spectrum-master/alsa.c:144: undefined reference to `snd_pcm_hw_params_get_rate'
/home/userKum/spectrum-master/alsa.c:151: undefined reference to`snd_pcm_hw_params_get_channels'
alsa.o: In function `open_alsa_write':
/home/userKum/spectrum-master/alsa.c:177: undefined reference to`snd_pcm_hw_params_sizeof'
/home/userKum/spectrum-master/alsa.c:177: undefined reference to `snd_pcm_hw_params_sizeof'
/home/userKum/spectrum-master/alsa.c:179: undefined reference to`snd_pcm_open'
/home/userKum/spectrum-master/alsa.c:185: undefined reference to `snd_pcm_hw_params_any'
/home/userKum/spectrum-master/alsa.c:192: undefined reference to`snd_pcm_hw_params_set_access'
/home/userKum/spectrum-master/alsa.c:199: undefined reference to `snd_pcm_hw_params_set_format'
/home/userKum/spectrum-master/alsa.c:206: undefined reference to`snd_pcm_hw_params_set_rate_resample'
/home/userKum/spectrum-master/alsa.c:213: undefined reference to `snd_pcm_hw_params_set_rate_near'
/home/userKum/spectrum-master/alsa.c:218: undefined reference to`snd_pcm_hw_params_set_channels_near'
/home/userKum/spectrum-master/alsa.c:223: undefined reference to `snd_pcm_hw_params'
/home/userKum/spectrum-master/alsa.c:194: undefined reference to`snd_pcm_close'
window.o: In function `sinc':
/home/userKum/spectrum-master/window.c:14: undefined reference to`sinf'
window.o: In function `hann':
/home/userKum/spectrum-master/window.c:24: undefined reference to`cosf'
window.o: In function `hamming':
/home/userKum/spectrum-master/window.c:29: undefined reference to`cosf'
window.o: In function `sinc':
/home/userKum/spectrum-master/window.c:14: undefined reference to`sinf'
window.o: In function `gauss':
/home/userKum/spectrum-master/window.c:38: undefined reference to`__expf_finite'
stft.o: In function `free_stft':
/home/userKum/spectrum-master/stft.c:44: undefined reference to`fftwf_destroy_plan'
stft.o: In function `get_stft':
/home/userKum/spectrum-master/stft.c:38: undefined reference to`cabsf'
stft.o: In function `create_stft':
/home/userKum/spectrum-master/stft.c:66: undefined reference to`fftwf_plan_dft_r2c_1d'
stft.o: In function `slide_stft':
/home/userKum/spectrum-master/stft.c:31: undefined reference to`fftwf_execute'
cqt.o: In function `get_cqt':
/home/userKum/spectrum-master/cqt.c:33: undefined reference to`cabsf'
cqt.o: In function `free_cqt':
/home/userKum/spectrum-master/cqt.c:47: undefined reference to`fftwf_destroy_plan'
cqt.o: In function `create_cqt':
/home/userKum/spectrum-master/cqt.c:65: undefined reference to`__logf_finite'
/home/userKum/spectrum-master/cqt.c:65: undefined reference to `__expf_finite'
/home/userKum/spectrum-master/cqt.c:66: undefined reference to`__log2_finite'
/home/userKum/spectrum-master/cqt.c:87: undefined reference to `fftwf_plan_dft_1d'
/home/userKum/spectrum-master/cqt.c:98: undefined reference to`cexpf'
/home/userKum/spectrum-master/cqt.c:103: undefined reference to `fftwf_execute'
/home/userKum/spectrum-master/cqt.c:57: undefined reference to`cabsf'
/home/userKum/spectrum-master/cqt.c:57: undefined reference to `cabsf'
/home/userKum/spectrum-master/cqt.c:115: undefined reference to`cabsf'
/home/userKum/spectrum-master/cqt.c:117: undefined reference to `cabsf'
/home/userKum/spectrum-master/cqt.c:117: undefined reference to`cabsf'
/home/userKum/spectrum-master/cqt.c:57: undefined reference to `__powf_finite'
/home/userKum/spectrum-master/cqt.c:139: undefined reference to`fftwf_destroy_plan'
/home/userKum/spectrum-master/cqt.c:146: undefined reference to `fftwf_plan_dft_r2c_1d'
cqt.o: In function`slide_cqt':
/home/userKum/spectrum-master/cqt.c:30: undefined reference to `fftwf_execute'
collect2: ld returned 1 exit status
make: **\* [spectrum] Error 1

**Comment by xdsopl** [comment]
That's because Ubuntu uses the "--no-copy-dt-needed-entries" option per default.
Fixed it in the Makefile, please pull.
Ahmet

**Comment by dikke** [comment]
Ahmet,  if I happen to meet you in person, I would bring you a bouquet and treat a super delicious meal. This is fantastic. You are brilliant.
